### ISSUE TITLE
Part 1 Section 5.4

### ISSUE THREAD

**Issue by mkelleh2** [ibm-blockchain-wsc/ImmersionWorkshop#11]
Just a readability issue... The commands that need to be issued look like comments because the "root@acd1f96d8807:/opt/gopath/src/github.com/hyperledger/fabric/peer#" ends in a hashtag. Makes it hard to see the command that needs to be run.

**Comment by silliman** [comment]
The hashtag at the end of the command prompt is unavoidable while running as root, but I can add a note in the lab prior to the first occurrence of entering a command as root that will alert the reader about this so they can take care not to confuse the subsequent command as a comment.

**Comment by silliman** [comment]
I've removed the comment about not having to enter comments, reducing the likelihood of confusion.  Fixed in commit c5e9648
